name: Release

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ inputs.tag || github.event.release.tag_name }}
  cancel-in-progress: true

jobs:
  build:
    name: Build GDExtension
    uses: ./.github/workflows/build.yml

  archive:
    needs: build
    name: Create & Upload Archive
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      RELEASE_TAG: ${{ inputs.tag || github.event.release.tag_name }}
      ADDON_PATH: addons/tellus
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.RELEASE_TAG }}
          # We only need the addon folder in the release archive.
          # This minimises what's checked out.
          sparse-checkout: demo/${{ env.ADDON_PATH }}
      - name: Download Binaries
        uses: actions/download-artifact@v4
        with:
          name: tellus
          path: demo/${{ env.ADDON_PATH }}/lib
      - id: create-archive
        name: Create Archive
        shell: sh
        working-directory: ./demo
        env:
          ARCHIVE_NAME: tellus-${{ env.RELEASE_TAG }}.zip
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Creating $ARCHIVE_NAME from ${{ env.ADDON_PATH }}"
          zip -r $ARCHIVE_NAME ${{ env.ADDON_PATH }}
          echo "Uploading $ARCHIVE_NAME to release ${{ env.RELEASE_TAG }}"
          gh release upload ${{ env.RELEASE_TAG }} $ARCHIVE_NAME
